insert into ORDER_ITEM(ORDER_ITEM_ID,ORDER_PRODUCT_ID,ORDER_ITEM_QUANTITY,ORDER_ITEM_PRODUCT_PRICE) values(1,'P001',2500,896.0);
insert into ORDER_ITEM(ORDER_ITEM_ID,ORDER_PRODUCT_ID,ORDER_ITEM_QUANTITY,ORDER_ITEM_PRODUCT_PRICE) values(2,'P002',458,56.0);
insert into ORDER_ITEM(ORDER_ITEM_ID,ORDER_PRODUCT_ID,ORDER_ITEM_QUANTITY,ORDER_ITEM_PRODUCT_PRICE) values(3,'P003',12358,890.70);
insert into ORDER_ITEM(ORDER_ITEM_ID,ORDER_PRODUCT_ID,ORDER_ITEM_QUANTITY,ORDER_ITEM_PRODUCT_PRICE) values(4,'P004',56,56.90);
insert into ORDER_ITEM(ORDER_ITEM_ID,ORDER_PRODUCT_ID,ORDER_ITEM_QUANTITY,ORDER_ITEM_PRODUCT_PRICE) values(5,'P005',781,56.0);
insert into ORDER_ITEM(ORDER_ITEM_ID,ORDER_PRODUCT_ID,ORDER_ITEM_QUANTITY,ORDER_ITEM_PRODUCT_PRICE) values(6,'P006',569,14.0);
insert into ORDER_ITEM(ORDER_ITEM_ID,ORDER_PRODUCT_ID,ORDER_ITEM_QUANTITY,ORDER_ITEM_PRODUCT_PRICE) values(7,'P007',12350,123.50);